<a href="https://colab.research.google.com/github/madrimovazaxro/Numpy-and-Pandas/blob/main/lesson3_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy library
import numpy as np
import time

lst = list(range(2000000))
arr = np.array(lst)

start = time.time()
lst2 = [x * 2 for x in lst]
print("List: ", time.time() - start)

start = time.time()
arr2 = arr * 2
print("Array: ", time.time() - start)

List:  0.16289281845092773
Array:  0.009382009506225586

In [ ]:
#1d and 2d arrays
arr = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])

print(arr)
print(arr2d)
print(arr2d[0][1])

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [6 7 8]]
2

In [ ]:
#functions of numpy: zeros(), ones(), full()
nollar = np.zeros((4, 4))
birlar = np.ones((2, 3))
yettilar = np.full((2, 3), 7)

print(nollar,"\n\n", birlar, "\n\n", yettilar)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[7 7 7]
 [7 7 7]]

In [ ]:
#arange() and linspace()
l1 = np.arange(0, 31, 2) #(start, stop, step)
l2 = np.linspace(1, 31, 15) #(start, stop, amount)

print(l1)
print(l2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 1.          3.14285714  5.28571429  7.42857143  9.57142857 11.71428571
 13.85714286 16.         18.14285714 20.28571429 22.42857143 24.57142857
 26.71428571 28.85714286 31.        ]

In [ ]:
#random library in numpy (rand() vs randint())
np.random.seed(42) #seed() used when we dont want to change the values
a = np.random.rand(3, 3) #float from 0 to 1
b = np.random.randint(0, 10, (3, 3)) #butun sonlar: from 0 to 10

print(a)
print(b)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
[[7 2 5]
 [4 1 7]
 [5 1 4]]

In [ ]:
#attributes of array
onlar = np.full((5, 5), 10)
print(onlar)
print(onlar.shape) #number of rows and cols
print(onlar.size) #rows*cols
print(onlar.ndim) #dimeansion
print(onlar.dtype) #data type

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
(5, 5)
25
2
int64

In [ ]:
#Indexing vs Slicing

#Indexing - indekslash
#Slicing - o'zimizga kerak joyini kesib olish

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::2]) #step=2
print(arr[2::]) #oxirgi 2tasi

1
4
[2 3 4]
[1 3]
[3 4]

In [ ]:
arr = np.random.randint(0, 10, (1,5))
print(arr)
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Standard Division: {np.std(arr)}")
print(f"Minimum Value: {np.min(arr)}")
print(f"Maximum Value: {np.max(arr)}")
print(f"Maximum Index: {np.argmax(arr)}") #argmin()

[[0 9 5 8 0]]
Sum: 22
Mean: 4.4
Standard Division: 3.826225293941798
Minimum Value: 0
Maximum Value: 9
Maximum Index: 1

In [ ]:
#pandas library
import pandas as pd
df = pd.read_csv("/talabalar - talabalar.csv.csv")
print(df.head())
print("\n\n")
print(df.tail())

                   ism  yosh    shahar          fan  baho  kurs
0     Hulkar Mirzayeva    23  Farg'ona   Geografiya    98     3
1        Jasur Holiqov    22    Termiz  Iqtisodiyot    97     1
2      Feruza Nazarova    25   Andijon     Adabiyot    66     1
3     Sherzod Tursunov    19   Andijon     Adabiyot    66     2
4  Lola Xudoyberdiyeva    24  Toshkent   Geografiya    97     3



                 ism  yosh     shahar         fan  baho  kurs
95  Kamola Normatova    24     Jizzax  Geografiya    80     1
96   Feruza Nazarova    26  Samarkand   Biologiya    70     3
97    Mansur Qosimov    24     Jizzax      Fizika    74     4
98    Barno Hamidova    22      Nukus       Tarix    74     3
99     Jasur Holiqov    20  Samarkand  Geografiya    65     1

In [ ]:
df.describe()

             yosh        baho        kurs
count  100.000000  100.000000  100.000000
mean    22.600000   77.080000    2.420000
std      2.651472   13.786745    1.147505
min     18.000000   55.000000    1.000000
25%     20.750000   65.000000    1.000000
50%     23.000000   77.500000    2.000000
75%     25.000000   89.500000    3.250000
max     26.000000  100.000000    4.000000

In [ ]:
df.shape

(100, 6)

In [ ]:
df.isnull().sum()

ism       0
yosh      0
shahar    0
fan       0
baho      0
kurs      0
dtype: int64

In [ ]:
!pip install opendatasets

Requirement already satisfied: opendatasets in /usr/local/lib/python3.12/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.3)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (2.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.4.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle->opendatasets) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle->opendatasets) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle->opendatasets) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle->opendatasets) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle->opendatasets) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle->opendatasets) (4.15.0)

In [ ]:
import opendatasets as od

In [ ]:
od.download("https://www.kaggle.com/competitions/titanic/data")

Skipping, found downloaded files in "./titanic" (use force=True to force download)

In [ ]:
df2 = pd.read_csv("/content/titanic/train.csv")
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df2.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df2.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df2.drop("Cabin", axis=1, inplace = True)

In [ ]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df[df['yosh'] == 24]

                    ism  yosh    shahar          fan  baho  kurs
4   Lola Xudoyberdiyeva    24  Toshkent   Geografiya    97     3
10     Nargiza Xoliqova    24     Nukus  Informatika    67     2
18       Firdavs Umarov    24  Farg'ona  Informatika    87     1
20       Malika Tosheva    24  Farg'ona    Biologiya    78     1
51       Temur Bahromov    24    Jizzax   Matematika    80     3
54       Ravshan Aminov    24   Andijon   Matematika    92     4
89     Zulfiya Rahimova    24    Qarshi        Tarix    93     1
93    Sevinch Razzaqova    24    Jizzax   Geografiya    72     3
95     Kamola Normatova    24    Jizzax   Geografiya    80     1
97       Mansur Qosimov    24    Jizzax       Fizika    74     4

In [ ]:
df[df['baho'] == 100]

                     ism  yosh    shahar       fan  baho  kurs
5       Zulfiya Rahimova    21     Nukus     Tarix   100     3
85  Gulnora Sotvoldiyeva    26  Toshkent     Kimyo   100     1
88        Temur Bahromov    20    Termiz  Adabiyot   100     2